services:
  - type: web
    name: odoo
    env: docker
    plan: free
    dockerfilePath: ./odoo/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true

  - type: pserv
    name: postgres
    env: docker
    plan: free
    dockerfilePath: ./db/Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true