services:
  - type: web
    name: aurafit-odoo
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: HOST
        value: db
      - key: USER
        value: odoo
      - key: PASSWORD
        value: odoo

  - type: pserv
    name: aurafit-db
    env: docker
    dockerfilePath: ./Dockerfile-db
    autoDeploy: false
    envVars:
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        value: odoo
